apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegrammy-backend-deployment
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: telegrammy-backend
  template:
    metadata:
      labels:
        app: telegrammy-backend
    spec:
      containers:
      - name: telegrammy-backend
        image: telegrammy/backend:3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: app-secret
