apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegrammy-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegrammy-frontend
  template:
    metadata:
      labels:
        app: telegrammy-frontend
    spec:
      containers:
      - name: telegrammy-frontend
        image: telegrammy/frontend:unittesting2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: frontend-config
