apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-vault-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-vault-role
rules:
- apiGroups: [ "" ]
  resources: [ "secrets" ]
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-vault-rb
subjects:
- kind: ServiceAccount
  name: eso-vault-sa
  namespace: default
roleRef:
  kind: Role
  name: eso-vault-role
  apiGroup: rbac.authorization.k8s.io
