apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "app-secret"
spec:
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  refreshInterval: "1s"
  target:
    name: app-secret
  dataFrom:
  - extract:
      key: secret/data/env
