apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: control-telegrammy-tech
  namespace: argocd
spec:
  secretName: control-telegrammy-tls-secret
  dnsNames:
  - control.telegrammy.tech
  issuerRef:
    name: certbot-issuer
    kind: ClusterIssuer