apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: telegrammy-tech
  namespace: default
spec:
  secretName: telegrammy-tls-secret
  dnsNames:
  - telegrammy.tech
  - sockets.telegrammy.tech
  issuerRef:
    name: certbot-issuer
    kind: ClusterIssuer
