apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-telegrammy-tech
  namespace: monitoring
spec:
  secretName: monitoring-telegrammy-tls-secret
  dnsNames:
  - monitor.telegrammy.tech
  issuerRef:
    name: certbot-issuer
    kind: ClusterIssuer